name: 'Build and Publish Docker Images'

env:
  # Push main branch only, else just build
  DOCKER_PUSH: ${{ github.ref == 'refs/heads/main' }}

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    # https://crontab.guru/
    - cron: '0 2 * * MON'

jobs:
  build:
    name: 'Build and Publish Docker Images'
    runs-on: ubuntu-latest

    steps:

      # https://github.com/actions/checkout
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: 'Setup QEMU'
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v1

      # https://github.com/marketplace/actions/docker-login
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images

      - name: 'Build and Push calibre-convert'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ env.DOCKER_PUSH }}
          tags: |
            vkhurana/calibre-convert
          build-args: |
            LABEL_VERSION=python3